[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pumpfun_sdk = "Fedqq2MDcAK2daypcvJTaquGUVufaFbSdVMof22mW98Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
